# Generated by Django 4.0.5 on 2023-11-05 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kutumb_website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='family_photos/')),
            ],
        ),
    ]
